name: 'Maintenance mode'

description: 'Manage maintenance mode status'

inputs:
  cloudflare-token:
    description: 'Cloudflare API token for enabling maintenance mode'
    required: true

  cloudflare-account-id:
    description: 'Cloudflare account ID'
    required: true

  cloudflare-kv-namespace-id:
    description: 'Cloudflare KV namespace ID for MAINTENANCE_PAGE_ENABLED flag'
    required: true

  command:
    description: "Command to execute. Either 'enable' or 'disable'"
    required: true

runs:
  using: "composite"
  steps:
    - name: "${{ inputs.command == 'enable' && 'Enable' || 'Disable' }} maintenance mode"
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
        CLOUDFLARE_KV_NAMESPACE_ID: ${{ inputs.cloudflare-kv-namespace-id }}
      shell: bash
      run: "./${{ inputs.command }}.sh"
